-- Quick Fix - Supabase/PostgreSQL schema
-- Based on the current Django SQLite models in backend/core/models.py.
-- Run this file in Supabase SQL Editor.

create table if not exists public.core_client (
  id bigint generated by default as identity primary key,
  full_name varchar(200) not null,
  email varchar(254) not null unique,
  phone varchar(30) not null,
  company varchar(200) not null default '',
  document varchar(30) not null default '',
  birth_date date null,
  address varchar(255) not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.core_professional (
  id bigint generated by default as identity primary key,
  full_name varchar(200) not null,
  email varchar(254) not null unique,
  phone varchar(30) not null,
  document varchar(30) not null default '',
  registration varchar(80) not null default '',
  resume_name varchar(255) not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.core_serviceorder (
  id bigint generated by default as identity primary key,
  client_id bigint null references public.core_client(id) on delete set null,
  title varchar(200) not null,
  service_type varchar(40) not null,
  type varchar(40) not null,
  status varchar(20) not null default 'analise',
  priority varchar(20) not null default 'media',
  professional varchar(200) not null default 'Aguardando atribuicao',
  estimated_time varchar(60) not null,
  description text not null default '',
  total_score double precision not null default 0,
  average_score double precision not null default 0,
  answers_count integer not null default 0,
  answers jsonb not null default '{}'::jsonb,
  questionnaire_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint core_serviceorder_status_check
    check (status in ('analise', 'em_andamento', 'concluido')),
  constraint core_serviceorder_priority_check
    check (priority in ('baixa', 'media', 'alta', 'urgente')),
  constraint core_serviceorder_answers_count_check
    check (answers_count >= 0)
);

create index if not exists core_serviceorder_client_id_idx
  on public.core_serviceorder(client_id);

create index if not exists core_serviceorder_status_idx
  on public.core_serviceorder(status);

create index if not exists core_serviceorder_priority_idx
  on public.core_serviceorder(priority);

create index if not exists core_serviceorder_created_at_idx
  on public.core_serviceorder(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_core_serviceorder_updated_at on public.core_serviceorder;

create trigger set_core_serviceorder_updated_at
before update on public.core_serviceorder
for each row
execute function public.set_updated_at();

-- Django backend access:
-- If your Django server connects with the Supabase database password, you can keep
-- Row Level Security disabled and let Django control access through its API.
alter table public.core_client disable row level security;
alter table public.core_professional disable row level security;
alter table public.core_serviceorder disable row level security;
