# Generated by Codex for the Quick Fix development backend.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=30)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("document", models.CharField(blank=True, max_length=30)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Professional",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=30)),
                ("document", models.CharField(blank=True, max_length=30)),
                ("registration", models.CharField(blank=True, max_length=80)),
                ("resume_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("service_type", models.CharField(max_length=40)),
                ("type", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("analise", "Em analise"),
                            ("em_andamento", "Em andamento"),
                            ("concluido", "Concluido"),
                        ],
                        default="analise",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                ("professional", models.CharField(default="Aguardando atribuicao", max_length=200)),
                ("estimated_time", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True)),
                ("total_score", models.FloatField(default=0)),
                ("average_score", models.FloatField(default=0)),
                ("answers_count", models.PositiveIntegerField(default=0)),
                ("answers", models.JSONField(default=dict)),
                ("questionnaire_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="core.client",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
